object Dependency {
    const val targetJvmVersion = "17"
    const val kotlinVersion = "1.7.22"
    const val springBootVersion = "3.0.4"
    const val springCloudVersion = "2022.0.1"
    const val restdocsapiSpecVersion = "0.18.2"
    const val liquibaseVersion = "4.10.0"
    const val sentryVersion = "6.15.0"
    const val mySQLConnectorVersion = "8.0.32"
    const val hibernateValidatorVersion = "8.0.0.Final"
    const val kotestVersion = "5.6.1"
    const val kotestSprintExtensions = "1.1.3"
    const val mockkVersion = "1.13.5"
    const val springMockkVersion = "4.0.2"
    const val jjwtVersion = "0.11.5"
    const val coroutinesVersion = "1.7.2"
}
